# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  
  # def change_log_since_last_tag
  #   # http://git-scm.com/docs/pretty-formats
  #   # <short hash> <commit title>
  #   return changelog_from_git_commits(
  #     pretty: '%h %s'
  #     tag_match_pattern: ''
  #   )
  # end
  
  TAG_GROUPING = "builds"
  
  def clear
    clear_derived_data
    xcclean
  end
  
  def get_change_log(grouping, lane)
    changelog_from_git_commits(
      pretty: '%h %s',
      tag_match_pattern: "#{grouping}/#{lane}/*"
    ) 
  end
  
  def add_tag(grouping, lane, build_number)
    add_git_tag(
      tag: "#{grouping}/#{lane}/#{build_number}"
    )
  end

  # fastlane release betaProd:BOOL betaStageGcloud:BOOL itunesConnect:BOOL
  lane :release do |options|
    increment_version_number
    increment_build_number
    
    #release betaStage allways
    betaStage
    buildTo = "Fabric Stage"

    if options[:betaProd]
      betaProd
      buildTo += "& Fabric Prod"
    end
    if options[:betaStageGcloud]
      betaStageGcloud
      buildTo += "& Fabric Stage Gcloud"
    end
    if options[:itunesConnect]
      itunesConnect
      buildTo += "& ItunesConnect"
    end
    
    commit_version_bump(
      message: "#{buildTo} build: #{get_build_number} version: #{get_version_number}"
    )
    push_to_git_remote(
      local_branch: "develop",
    )
  end
  
  private_lane :betaStage do
    clear
    
    lane_name = "betaStage"
    change_log = get_change_log(TAG_GROUPING, lane_name)
    add_tag(TAG_GROUPING, lane_name, get_build_number)
  end
  
  private_lane :betaProd do
    clear
    
    lane_name = "betaProd"
    change_log = get_change_log(TAG_GROUPING, lane_name)
    add_tag(TAG_GROUPING, lane_name, get_build_number)
  end
  
  private_lane :betaStageGcloud do
    clear
    
    lane_name = "betaStageGcloud"
    change_log = get_change_log(TAG_GROUPING, lane_name)
    add_tag(TAG_GROUPING, lane_name, get_build_number)
  end
  
  private_lane :itunesConnect do
    clear
    
    lane_name = "itunesConnect"
    change_log = get_change_log(TAG_GROUPING, lane_name)
    add_tag(TAG_GROUPING, lane_name, get_build_number)
  end
end
