# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  
  def change_log_since_last_tag
    # http://git-scm.com/docs/pretty-formats
    # <short hash> <commit title>
    return changelog_from_git_commits(pretty: '%h %s')
  end
  
  lane :betaStage do
    clear_derived_data
    xcclean

    increment_version_number # Automatically increment patch version number
    increment_build_number # automatically increment by one


    #build your iOS app
    gym(
      output_directory: 'Exports_Stage',
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        compileBitcode: false,
      }
    )
    
    change_log = change_log_since_last_tag
    print change_log
    
    add_git_tag
  end

  lane :betaProd do
    clear_derived_data
    xcclean

    gym(
      output_directory: 'Exports_Prod',
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        compileBitcode: false,
      }
    )
    
    change_log = change_log_since_last_tag
    print change_log 
  
    add_git_tag
  end
end
